### PR TITLE
Fix fixUTF8() cast

### PR DESCRIPTION
**Pull request by mmarynich**
The method fixUTF8() casts all the values of an array to string (int, float, bool).

### CODE REVIEW

**Comment by mmarynich** [comment]
Is there anybody?

**Comment by neitanod** [comment]
Sorry I didn't see your message before.

**Comment by mmarynich** [comment]
thanks @neitanod 

Could you make a new release please ?

**Comment by neitanod** [comment]
I just did.  Could you try it and tell me if the release is visible for you
composer?

Thanks!

**Pull request merged**
