### PR TITLE
PhpDocBlocks

### PR DESCRIPTION
**Pull request by Tyres91**
I add the Doc Blocks for Methods

### CODE REVIEW

**Comment by j0k3r** [comment]
Sorry, but it adds no value at all.

**Comment by demis-palma** [comment]
@Tyres91 this is really appreciated, thanks.
@j0k3r, you will discover the value of Doc Blocks one day.

**Comment by j0k3r** [comment]
@demis-palma I'll see more value in that if there are actually information in the doc bloc, instead of default generated one ...

**Comment by demis-palma** [comment]
To me it is better than it was before.
In addition, belittle the work of other people, won't get better results from them.

**Comment by neitanod** [comment]
This pull request has conflicts now.
If someone is kind enough to send an updated pull request for this, I promise I'll get noticed and merge it this time.

**Pull request closed without merging**
