### PR TITLE
Method to fix utf8 from any array

### PR DESCRIPTION
**Pull request by raulinoneto**
Thank you very much to your class, helped to solve the many problems in the project in which I am part. I've added a method to be used to fix arrays, which is very useful in json_encode's that return "Malformed UTF-8 characters, possibly incorrectly encoded". I hope to add a lot to this class that helped me a lot.

### CODE REVIEW

**Comment by neitanod** [comment]
Isn't this functionality already part of fixUTF8?

**Comment by garrettw** [comment]
[I'd say so.](https://github.com/neitanod/forceutf8/blob/master/src/ForceUTF8/Encoding.php#L269)

**Comment by raulinoneto** [comment]
Exists in fixUTF8 function, but doesn't works with multidimensional array and doesn't fix the keys of the array.

**Comment by raulinoneto** [comment]
I'll addict the options.

**Comment by neitanod** [comment]
I believe that it now works in multidimentional arrays as well.
I'd seriously recommend using an external function to alter array keys. 
I think the API should be as simple as possible (it already grew more complicated than I initially wanted) instead of including functionality for such specific needs.
Also altering array keys silently seems counter intuitive and could be considered an undesired side effect in most cases.

**Pull request closed without merging**
